name: Actualizador de P2P Bybit y Yadio

on:
  schedule:
    - cron: '*/18 9-23,0-4 * * *'
  workflow_dispatch: 

jobs:
  actualizar-p2p:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Subimos a 3.10 para mejor compatibilidad

      - name: Instalar Dependencias
        run: |
          pip install requests
          pip install -U pyDolarVenezuela  # El -U asegura que se actualice a la última versión

      - name: Correr Script P2P
        run: python Tasasapp.py

      - name: Guardar cambios en el repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add tasas.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Tasas actualizadas" && git push)
